# Generated by Django 5.2 on 2025-05-04 13:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
